### PR TITLE
Add copyright header - Irrelevant 

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by RDIL** [comment]
@GamingGeek requesting review

**Comment by kierandrewett** [comment]
Excuse me?

**Comment by RDIL** [comment]
?

**Comment by kierandrewett** [comment]
No point in the PR, closing.

**Comment by GamingGeek** [comment]
It's a valid addition, so I see no reason to not merge? @EnderDev any specific reason why?

**Comment by Blizma** [comment]
Good reason.

**Comment by GamingGeek** [comment]
Why do you hate him?

**Comment by EnderDev** [comment]
Thanks Blizma, also I don't understand why this random dude got invited into org, with a reason "he wants the record for the most organisations". Yeah no, not happening.

**Comment by RDIL** [comment]
RIP
why do you hate me

**Comment by EnderDev** [comment]
Idk, @GamingGeek randomly invited you in here, when you don't even know Skript.

**Comment by Blizma** [comment]
uhhh, 2 of the orgs are owned by him and he is the only member, and also the record of most organisations is dumb because... fuck, i can beat that record myself on my own.

**Comment by EnderDev** [comment]
lmao

**Comment by Blizma** [comment]
love [your website by the way](https://superquizsite.github.io/#)

**Comment by GamingGeek** [comment]
pretty sure he doesn't like you since you've worked with Sk1er in the past and he doesn't like sk1er for some odd reason. I *still* see no reason not to merge

**Comment by Blizma** [comment]
well, it's in a org where he's the only member

**Comment by RDIL** [comment]
Alright alright,
No need to bully me.  I'm just trying to help out your project, but you two are being dicks.  I ask for a review from the ONE PERSON I KNOW in the organization, and you take personal offense??  Also, I want to set a record for most organizations, just a personal goal, why do you care?  Also, NONE of the organizations I'm in have 0 people (a thing called private membership exists).  So, yeah, just getting my side out.

**Pull request closed without merging**
